Added Heston and CEV models
JJJerome/mbt_gym pull request #15
Opened 2022-10-25 21:51 UTC by NirmaySriharsha

2022-10-26 11:23 UTC, JJJerome requested changes
This looks good!

The only real change I would suggest is to use the Euler scheme for the asset price in the Heston model. Also some nitpicking.

2022-10-26 11:23 UTC, JJJerome commented on mbt_gym/stochastic_processes/midprice_models.py
> +        self.current_state[:,0] = self.current_state[:,0]*np.exp((self.drift - self.current_state[:,1]/2)*self.step_size
I think that updates should be written using the Euler scheme of the process. Perhaps something along the lines of: https://www.quantstart.com/articles/Heston-Stochastic-Volatility-Model-with-Euler-Discretisation-in-C/ 

This is for two reasons:
(1) I am not 100% convinced that you can write the Heston in this explicit form. Have you got a reference fo how you coded it up?
(2) By removing the (fairly costly) exponential, simulation should be sped up a bit. 

P.S. I noted that the GBM implementation also uses the exponential, and I will change that.

2022-10-26 11:23 UTC, JJJerome commented on mbt_gym/stochastic_processes/midprice_models.py
> +class ConstantElasticityofVarianceMidpriceModel(MidpriceModel):
Capital O for of

2022-10-26 13:10 UTC, NirmaySriharsha commented
Added a Euler scheme. I actually don't exactly remember what's going on with self.max_depth in TradingEnvironment. I remember when I ran check_all_imports.py the TradingEnvironment.py file was throwing up errors because the default value for max_depth is None and that particular section of code was interpreting it as a float. I think what I did was just a temporary workaround to get past some meaningless type errors. Discard those changes if they're not necessary.

2022-10-26 13:59 UTC, JJJerome submitted a review, later dismissed

2022-10-26 14:03 UTC, leandro-sbetancourt approved these changes

2022-10-26 15:05 UTC, NirmaySriharsha commented
I don't have write access permission to merge.

2022-10-27 09:43 UTC, JJJerome approved these changes
LGTM! Will merge.

2022-10-27 09:43 UTC, merged